import type { EngineRuleMapping } from '../schema.js';
import { asRequirementId } from '../ids.js';

// axe-core rule -> WCAG requirement(s). GENERATED from axe-core metadata (each
// axe rule carries a wcagNNN tag naming its success criterion), then curated:
// rules whose SC has a registry requirement are mapped; the rest are recorded in
// AXE_UNMAPPED_INTENTIONAL with a reason (SC not yet in the registry, or a
// best-practice rule with no legal hook). AXE_ALL_RULES is the full rule set at
// the pinned version — test/axe-drift.test.ts asserts the installed axe matches
// it AND that mapped + unmapped partition it exactly, so an axe upgrade that
// adds a rule fails CI until the new rule is categorized (build-plan §engine
// exhaustiveness). verify.ts checks the mapped subset is internally consistent.

export const AXE_VERSION = '4.10.3';

type Row = [rule: string, requirement: string];

const MAPPED: Row[] = [
  ['area-alt', 'wcag22.2.4.4'],
  ['aria-allowed-attr', 'wcag22.4.1.2'],
  ['aria-braille-equivalent', 'wcag22.4.1.2'],
  ['aria-command-name', 'wcag22.4.1.2'],
  ['aria-conditional-attr', 'wcag22.4.1.2'],
  ['aria-deprecated-role', 'wcag22.4.1.2'],
  ['aria-hidden-body', 'wcag22.1.3.1'],
  ['aria-hidden-focus', 'wcag22.4.1.2'],
  ['aria-input-field-name', 'wcag22.4.1.2'],
  ['aria-meter-name', 'wcag22.1.1.1'],
  ['aria-progressbar-name', 'wcag22.1.1.1'],
  ['aria-prohibited-attr', 'wcag22.4.1.2'],
  ['aria-required-attr', 'wcag22.4.1.2'],
  ['aria-required-children', 'wcag22.1.3.1'],
  ['aria-required-parent', 'wcag22.1.3.1'],
  ['aria-roledescription', 'wcag22.4.1.2'],
  ['aria-roles', 'wcag22.4.1.2'],
  ['aria-toggle-field-name', 'wcag22.4.1.2'],
  ['aria-tooltip-name', 'wcag22.4.1.2'],
  ['aria-valid-attr', 'wcag22.4.1.2'],
  ['aria-valid-attr-value', 'wcag22.4.1.2'],
  ['audio-caption', 'wcag22.1.2.1'],
  ['autocomplete-valid', 'wcag22.1.3.5'],
  ['avoid-inline-spacing', 'wcag22.1.4.12'],
  ['blink', 'wcag22.2.2.2'],
  ['button-name', 'wcag22.4.1.2'],
  ['bypass', 'wcag22.2.4.1'],
  ['color-contrast', 'wcag22.1.4.3'],
  ['css-orientation-lock', 'wcag22.1.3.4'],
  ['definition-list', 'wcag22.1.3.1'],
  ['dlitem', 'wcag22.1.3.1'],
  ['document-title', 'wcag22.2.4.2'],
  ['duplicate-id', 'wcag22.4.1.1'],
  ['duplicate-id-active', 'wcag22.4.1.1'],
  ['duplicate-id-aria', 'wcag22.4.1.2'],
  ['form-field-multiple-labels', 'wcag22.3.3.2'],
  ['frame-focusable-content', 'wcag22.2.1.1'],
  ['frame-title', 'wcag22.4.1.2'],
  ['frame-title-unique', 'wcag22.4.1.2'],
  ['html-has-lang', 'wcag22.3.1.1'],
  ['html-lang-valid', 'wcag22.3.1.1'],
  ['html-xml-lang-mismatch', 'wcag22.3.1.1'],
  ['image-alt', 'wcag22.1.1.1'],
  ['input-button-name', 'wcag22.4.1.2'],
  ['input-image-alt', 'wcag22.1.1.1'],
  ['label', 'wcag22.4.1.2'],
  ['label-content-name-mismatch', 'wcag22.2.5.3'],
  ['link-in-text-block', 'wcag22.1.4.1'],
  ['link-name', 'wcag22.2.4.4'],
  ['list', 'wcag22.1.3.1'],
  ['listitem', 'wcag22.1.3.1'],
  ['marquee', 'wcag22.2.2.2'],
  ['meta-refresh', 'wcag22.2.2.1'],
  ['meta-viewport', 'wcag22.1.4.4'],
  ['nested-interactive', 'wcag22.4.1.2'],
  ['no-autoplay-audio', 'wcag22.1.4.2'],
  ['object-alt', 'wcag22.1.1.1'],
  ['p-as-heading', 'wcag22.1.3.1'],
  ['role-img-alt', 'wcag22.1.1.1'],
  ['scrollable-region-focusable', 'wcag22.2.1.1'],
  ['select-name', 'wcag22.4.1.2'],
  ['server-side-image-map', 'wcag22.2.1.1'],
  ['summary-name', 'wcag22.4.1.2'],
  ['svg-img-alt', 'wcag22.1.1.1'],
  ['table-fake-caption', 'wcag22.1.3.1'],
  ['target-size', 'wcag22.2.5.8'],
  ['td-has-header', 'wcag22.1.3.1'],
  ['td-headers-attr', 'wcag22.1.3.1'],
  ['th-has-data-cells', 'wcag22.1.3.1'],
  ['valid-lang', 'wcag22.3.1.2'],
  ['video-caption', 'wcag22.1.2.2'],
];

/** axe rules deliberately not mapped yet, with why. Keeps the partition honest. */
export const AXE_UNMAPPED_INTENTIONAL: Array<[rule: string, reason: string]> = [
  ['accesskeys', 'best-practice / non-WCAG'],
  ['aria-allowed-role', 'best-practice / non-WCAG'],
  ['aria-dialog-name', 'best-practice / non-WCAG'],
  ['aria-text', 'best-practice / non-WCAG'],
  ['aria-treeitem-name', 'best-practice / non-WCAG'],
  ['color-contrast-enhanced', 'wcag 1.4.6 not in registry'],
  ['empty-heading', 'best-practice / non-WCAG'],
  ['empty-table-header', 'best-practice / non-WCAG'],
  ['focus-order-semantics', 'best-practice / non-WCAG'],
  ['frame-tested', 'best-practice / non-WCAG'],
  ['heading-order', 'best-practice / non-WCAG'],
  ['hidden-content', 'best-practice / non-WCAG'],
  ['identical-links-same-purpose', 'wcag 2.4.9 not in registry'],
  ['image-redundant-alt', 'best-practice / non-WCAG'],
  ['label-title-only', 'best-practice / non-WCAG'],
  ['landmark-banner-is-top-level', 'best-practice / non-WCAG'],
  ['landmark-complementary-is-top-level', 'best-practice / non-WCAG'],
  ['landmark-contentinfo-is-top-level', 'best-practice / non-WCAG'],
  ['landmark-main-is-top-level', 'best-practice / non-WCAG'],
  ['landmark-no-duplicate-banner', 'best-practice / non-WCAG'],
  ['landmark-no-duplicate-contentinfo', 'best-practice / non-WCAG'],
  ['landmark-no-duplicate-main', 'best-practice / non-WCAG'],
  ['landmark-one-main', 'best-practice / non-WCAG'],
  ['landmark-unique', 'best-practice / non-WCAG'],
  ['meta-refresh-no-exceptions', 'wcag 2.2.4 not in registry'],
  ['meta-viewport-large', 'best-practice / non-WCAG'],
  ['page-has-heading-one', 'best-practice / non-WCAG'],
  ['presentation-role-conflict', 'best-practice / non-WCAG'],
  ['region', 'best-practice / non-WCAG'],
  ['scope-attr-valid', 'best-practice / non-WCAG'],
  ['skip-link', 'best-practice / non-WCAG'],
  ['tabindex', 'best-practice / non-WCAG'],
  ['table-duplicate-name', 'best-practice / non-WCAG'],
];

export const AXE_MAPPINGS: EngineRuleMapping[] = MAPPED.map(([engineRule, req]) => ({
  engine: 'axe-core',
  engineVersion: AXE_VERSION,
  engineRule,
  requirements: [asRequirementId(req)],
  // axe 'violation' results are high-confidence; 'incomplete' results are
  // downgraded to needs-review by the collector regardless of this maximum.
  confidence: 'violation',
}));

/** The mapped rules — the pinned set verify.ts checks for exhaustiveness. */
export const AXE_PINNED_RULES: string[] = MAPPED.map(([rule]) => rule);

/** Every rule id axe ships at AXE_VERSION — the upgrade-drift snapshot. */
export const AXE_ALL_RULES: string[] = [
  'accesskeys',
  'area-alt',
  'aria-allowed-attr',
  'aria-allowed-role',
  'aria-braille-equivalent',
  'aria-command-name',
  'aria-conditional-attr',
  'aria-deprecated-role',
  'aria-dialog-name',
  'aria-hidden-body',
  'aria-hidden-focus',
  'aria-input-field-name',
  'aria-meter-name',
  'aria-progressbar-name',
  'aria-prohibited-attr',
  'aria-required-attr',
  'aria-required-children',
  'aria-required-parent',
  'aria-roledescription',
  'aria-roles',
  'aria-text',
  'aria-toggle-field-name',
  'aria-tooltip-name',
  'aria-treeitem-name',
  'aria-valid-attr',
  'aria-valid-attr-value',
  'audio-caption',
  'autocomplete-valid',
  'avoid-inline-spacing',
  'blink',
  'button-name',
  'bypass',
  'color-contrast',
  'color-contrast-enhanced',
  'css-orientation-lock',
  'definition-list',
  'dlitem',
  'document-title',
  'duplicate-id',
  'duplicate-id-active',
  'duplicate-id-aria',
  'empty-heading',
  'empty-table-header',
  'focus-order-semantics',
  'form-field-multiple-labels',
  'frame-focusable-content',
  'frame-tested',
  'frame-title',
  'frame-title-unique',
  'heading-order',
  'hidden-content',
  'html-has-lang',
  'html-lang-valid',
  'html-xml-lang-mismatch',
  'identical-links-same-purpose',
  'image-alt',
  'image-redundant-alt',
  'input-button-name',
  'input-image-alt',
  'label',
  'label-content-name-mismatch',
  'label-title-only',
  'landmark-banner-is-top-level',
  'landmark-complementary-is-top-level',
  'landmark-contentinfo-is-top-level',
  'landmark-main-is-top-level',
  'landmark-no-duplicate-banner',
  'landmark-no-duplicate-contentinfo',
  'landmark-no-duplicate-main',
  'landmark-one-main',
  'landmark-unique',
  'link-in-text-block',
  'link-name',
  'list',
  'listitem',
  'marquee',
  'meta-refresh',
  'meta-refresh-no-exceptions',
  'meta-viewport',
  'meta-viewport-large',
  'nested-interactive',
  'no-autoplay-audio',
  'object-alt',
  'p-as-heading',
  'page-has-heading-one',
  'presentation-role-conflict',
  'region',
  'role-img-alt',
  'scope-attr-valid',
  'scrollable-region-focusable',
  'select-name',
  'server-side-image-map',
  'skip-link',
  'summary-name',
  'svg-img-alt',
  'tabindex',
  'table-duplicate-name',
  'table-fake-caption',
  'target-size',
  'td-has-header',
  'td-headers-attr',
  'th-has-data-cells',
  'valid-lang',
  'video-caption',
];
