import type { KnowledgeEntryInput } from './schema.js';
import { CONTROL_FACTS } from './control.js';

export { CONTROL_VENDOR_IDS } from './control.js';

// Seed knowledge base. Every entry is a PROPOSAL (proposedBy 'complykit-seed',
// no confirmedBy): it lets the first scans name the common vendors, and each
// one waits for a human to confirm it through the research workflow (§4.2).
// Order matters — first match wins — so path-specific entries on shared hosts
// (google.com) come before broader ones.
//
// Sources are the vendors' own documentation roots. No data here is copied
// from the non-commercial tracker databases (Tracker Radar / Disconnect /
// Ghostery) — this repository is public (plans/consent-design.md §4.4).

const SEEDED = '2026-10-02';
const seed = (e: Omit<KnowledgeEntryInput, 'provenance'> & { sources?: string[] }): KnowledgeEntryInput => {
  const { sources, ...rest } = e;
  return { ...rest, provenance: { proposedBy: 'complykit-seed', proposedAt: SEEDED, sources: sources ?? [] } };
};

const GOOGLE_CONSENT = 'https://developers.google.com/tag-platform/security/guides/consent';

const BASE_ENTRIES: KnowledgeEntryInput[] = [
  // --- Google ---------------------------------------------------------------
  seed({
    id: 'google.analytics',
    vendor: 'Google Analytics 4',
    owner: 'Google LLC',
    match: { hosts: ['google-analytics.com', 'analytics.google.com'], inline: ['\\bgtag\\s*\\(\\s*[\'"]config[\'"]\\s*,\\s*[\'"]G-', 'google-analytics\\.com/(analytics|ga)\\.js', 'googletagmanager\\.com/gtag/js\\?id=G-', '\\bgtag\\s*\\(\\s*["\']config["\']\\s*,\\s*["\'](G|UA)-', '\\bga\\s*\\(\\s*["\']create["\']'] },
    categories: ['analytics'],
    sends: ['page-address', 'page-title', 'browser-id', 'event-name'],
    stores: [{ name: '^_ga(_.+)?$', kind: 'cookie', lifetimeDays: 400 }],
    consentApi: "Google Consent Mode — gtag('consent', 'update', {analytics_storage})",
    decoder: 'google',
    notes: 'Consent Mode "advanced" still sends cookieless pings with consent denied — decoded, not counted as consented traffic.',
    sources: [GOOGLE_CONSENT, 'https://support.google.com/analytics/answer/11397207'],
  }),
  seed({
    id: 'google.ads.ccm',
    vendor: 'Google Ads (conversion / remarketing)',
    owner: 'Google LLC',
    match: { hosts: ['google.com', 'google.co.uk', 'google.de', 'google.ca'], path: '^/(pagead|ccm|rmkt|ads)/', inline: ['\\bgtag\\s*\\(\\s*[\'"]config[\'"]\\s*,\\s*[\'"]AW-', 'googletagmanager\\.com/gtag/js\\?id=AW-', '\\bgtag\\s*\\(\\s*["\']config["\']\\s*,\\s*["\']AW-', 'googleadservices\\.com/pagead/conversion'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'click-id'],
    consentApi: "Google Consent Mode — ad_storage, ad_user_data, ad_personalization",
    decoder: 'google',
    restrictedMode: 'rdp=1 (restricted data processing) / npa=1',
    sources: [GOOGLE_CONSENT],
  }),
  seed({
    id: 'google.recaptcha',
    vendor: 'Google reCAPTCHA',
    owner: 'Google LLC',
    match: { hosts: ['google.com', 'recaptcha.net', 'gstatic.com'], path: '^/recaptcha/' },
    categories: ['captcha'],
    consentApi: 'none — load only where the form needs it',
    notes: 'EU DPAs have treated reCAPTCHA on page load (not on interaction) as needing consent.',
    sources: ['https://developers.google.com/recaptcha'],
  }),
  seed({
    id: 'google.ads.doubleclick',
    vendor: 'Google Marketing Platform (DoubleClick)',
    owner: 'Google LLC',
    match: { hosts: ['doubleclick.net', 'googleadservices.com', 'googlesyndication.com', 'googletagservices.com', 'adservice.google.com'], inline: ['googletagmanager\\.com/gtag/js\\?id=DC-', 'fls\\.doubleclick\\.net/', 'googlesyndication\\.com/'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'click-id'],
    stores: [{ name: '^(IDE|test_cookie|DSID)$', kind: 'cookie', lifetimeDays: 390 }, { name: '^_gcl_', kind: 'cookie', lifetimeDays: 90 }, { name: '^GCL_AW_P$', kind: 'local' }],
    consentApi: 'Google Consent Mode — ad_storage, ad_user_data, ad_personalization',
    decoder: 'google',
    restrictedMode: 'rdp=1 / npa=1',
    sources: [GOOGLE_CONSENT],
  }),
  seed({
    id: 'google.tag-manager',
    vendor: 'Google Tag Manager / gtag.js',
    owner: 'Google LLC',
    match: { hosts: ['googletagmanager.com'], inline: ['\\bGTM-[A-Z0-9]{4,10}\\b', 'googletagmanager\\.com/gtm\\.js', '["\']dataLayer["\']\\s*,\\s*["\']GTM-'] },
    categories: ['tag-manager'],
    sends: ['page-address'],
    consentApi: 'loads other tags; gate those, and set Consent Mode defaults before it loads',
    decoder: 'google',
    notes: 'Loading the container script sends the page address to Google; whether that alone needs consent is unsettled.',
    sources: ['https://developers.google.com/tag-platform/tag-manager'],
  }),
  seed({
    id: 'google.fonts',
    vendor: 'Google Fonts',
    owner: 'Google LLC',
    match: { hosts: ['fonts.googleapis.com', 'fonts.gstatic.com'] },
    categories: ['fonts'],
    consentApi: 'none — self-host the fonts',
    notes: 'LG München (2022) held loading Google Fonts from Google’s servers without consent unlawful in DE.',
    sources: ['https://developers.google.com/fonts/faq/privacy'],
  }),
  seed({
    id: 'google.maps',
    vendor: 'Google Maps',
    owner: 'Google LLC',
    match: { hosts: ['maps.googleapis.com', 'maps.gstatic.com'] },
    categories: ['embed'],
    consentApi: 'none — load on interaction (two-click facade)',
    sources: ['https://developers.google.com/maps'],
  }),
  seed({
    id: 'google.youtube',
    vendor: 'YouTube embed',
    owner: 'Google LLC',
    match: { hosts: ['youtube.com', 'youtube-nocookie.com', 'ytimg.com', 'googlevideo.com'] },
    categories: ['embed'],
    stores: [{ name: '^(VISITOR_INFO1_LIVE|YSC|VISITOR_PRIVACY_METADATA)$', kind: 'cookie', lifetimeDays: 180 }, { name: '^(__Secure-.+|__sak|GPS|PREF|LOGIN_INFO|TESTCOOKIESENABLED)$', kind: 'cookie' }, { name: '^(yt-.+|ytidb::.+|yt\\..+|LAST_RESULT_ENTRY_KEY)$', kind: 'local' }],
    consentApi: 'none — youtube-nocookie limits personalization only; use a click-to-load facade',
    sources: ['https://support.google.com/youtube/answer/171780'],
  }),
  seed({
    id: 'google.services',
    vendor: 'Google (google.com services)',
    owner: 'Google LLC',
    // Everything on google.com the path-specific entries above didn't claim.
    match: { hosts: ['google.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    stores: [{ name: '^(NID|AEC|1P_JAR|SOCS|__Secure-ENID)$', kind: 'cookie', lifetimeDays: 183 }],
    consentApi: 'none for widgets — load on interaction or after consent',
    notes: 'Widgets served from google.com (e.g. the merchant-review badge) set NID, which Google’s cookie policy lists for ads in Google services.',
    sources: ['https://policies.google.com/technologies/cookies'],
  }),
  seed({
    id: 'google.static',
    vendor: 'Google static assets',
    owner: 'Google LLC',
    match: { hosts: ['gstatic.com', 'googleapis.com'] },
    categories: ['cdn'],
    sources: ['https://policies.google.com/technologies'],
  }),

  // --- Meta -----------------------------------------------------------------
  seed({
    id: 'meta.pixel',
    vendor: 'Meta Pixel',
    owner: 'Meta Platforms, Inc.',
    match: { hosts: ['facebook.com', 'facebook.net', 'fbcdn.net'], inline: ['\\bfbq\\s*\\(', 'connect\\.facebook\\.net/[^"\'\\s]*fbevents\\.js', 'facebook\\.com/tr[/?]'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'hashed-email', 'event-name', 'click-id'],
    stores: [{ name: '^_fb[pc]$', kind: 'cookie', lifetimeDays: 90 }],
    consentApi: "fbq('consent', 'revoke' | 'grant'); limited data use via fbq('dataProcessingOptions', ['LDU'], 0, 0)",
    decoder: 'meta',
    restrictedMode: 'Limited Data Use (dpo=LDU)',
    sources: ['https://developers.facebook.com/docs/meta-pixel/', 'https://developers.facebook.com/docs/marketing-apis/data-processing-options'],
  }),
  seed({
    id: 'meta.instagram',
    vendor: 'Instagram embed',
    owner: 'Meta Platforms, Inc.',
    match: { hosts: ['instagram.com', 'cdninstagram.com'] },
    categories: ['embed'],
    sources: ['https://developers.facebook.com/docs/instagram-platform/embed'],
  }),

  // --- Other ad platforms ---------------------------------------------------
  seed({
    id: 'tiktok.pixel',
    vendor: 'TikTok Pixel',
    owner: 'TikTok Pte. Ltd. / ByteDance',
    match: { hosts: ['analytics.tiktok.com', 'tiktok.com', 'tiktokcdn.com', 'tiktokw.us', 'ttwstatic.com'], inline: ['\\bttq\\.(load|page|track|identify)\\s*\\(', 'analytics\\.tiktok\\.com/i18n/pixel/events\\.js'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'hashed-email', 'event-name', 'click-id'],
    stores: [{ name: '^_ttp$', kind: 'cookie', lifetimeDays: 390 }, { name: '^ttcsid', kind: 'cookie' }],
    consentApi: 'ttq.holdConsent() / ttq.grantConsent() / ttq.revokeConsent()',
    decoder: 'tiktok',
    restrictedMode: 'limited_data_use',
    sources: ['https://ads.tiktok.com/help/article/get-started-pixel'],
  }),
  seed({
    id: 'microsoft.uet',
    vendor: 'Microsoft Advertising UET',
    owner: 'Microsoft Corporation',
    match: { hosts: ['bat.bing.com', 'bat.bing.net', 'bing.com'], inline: ['\\buetq\\b', 'bat\\.bing\\.com/bat\\.js'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'click-id'],
    stores: [{ name: '^_uet(sid|vid)$', kind: 'cookie', lifetimeDays: 390 }, { name: '^(MUID|SRM_B|SRCHD|SRCHUID|SRCHUSR|_EDGE_S|_EDGE_V)$', kind: 'cookie', lifetimeDays: 390 }],
    consentApi: "window.uetq.push('consent', 'update', {ad_storage})",
    decoder: 'microsoft',
    sources: ['https://learn.microsoft.com/en-us/advertising/guides/universal-event-tracking'],
  }),
  seed({
    id: 'microsoft.clarity',
    vendor: 'Microsoft Clarity',
    owner: 'Microsoft Corporation',
    match: { hosts: ['clarity.ms'], inline: ['[\'"]clarity[\'"]\\s*,\\s*[\'"]script[\'"]', '\\bclarity\\s*\\(\\s*[\'\\"]', 'clarity\\.ms/tag/', '"clarity"\\s*,\\s*"script"', '\\bclarity\\s*\\(\\s*["\'](set|identify|consent|event)["\']'] },
    categories: ['session-recording', 'analytics'],
    sends: ['page-address', 'browser-id', 'interactions'],
    // _clck/_clsk on the site; CLID, MR, SM, ANONCHK on clarity.ms / bing.com (Clarity's collection).
    stores: [{ name: '^_cl(ck|sk)$', kind: 'cookie', lifetimeDays: 365 }, { name: '^(CLID|MR|SM|ANONCHK|_cltk)$', kind: 'cookie', lifetimeDays: 365 }],
    consentApi: "clarity('consentv2', {ad_Storage, analytics_Storage})",
    sources: ['https://learn.microsoft.com/en-us/clarity/setup-and-installation/clarity-consent-api-v2', 'https://learn.microsoft.com/en-us/clarity/setup-and-installation/cookie-list'],
  }),
  seed({
    id: 'linkedin.insight',
    vendor: 'LinkedIn Insight Tag',
    owner: 'LinkedIn Corporation (Microsoft)',
    match: { hosts: ['px.ads.linkedin.com', 'snap.licdn.com', 'linkedin.com', 'licdn.com'], inline: ['\\b_linkedin_partner_id\\b', '\\blintrk\\s*\\(', 'snap\\.licdn\\.com/li\\.lms-analytics/insight\\.min\\.js', '_linkedin_partner_id'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    stores: [{ name: '^(li_sugr|bcookie|lidc|UserMatchHistory|AnalyticsSyncHistory|li_fat_id)$', kind: 'cookie', lifetimeDays: 90 }],
    consentApi: 'none documented — must be held back',
    sources: ['https://www.linkedin.com/help/lms/answer/a427660'],
  }),
  seed({
    id: 'pinterest.tag',
    vendor: 'Pinterest Tag',
    owner: 'Pinterest, Inc.',
    match: { hosts: ['ct.pinterest.com', 'pinterest.com', 'pinimg.com'], inline: ['\\bpintrk\\s*\\(', 's\\.pinimg\\.com/ct/core\\.js'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'hashed-email', 'event-name'],
    stores: [{ name: '^_pin_unauth$|^_pinterest_', kind: 'cookie', lifetimeDays: 365 }],
    consentApi: "pintrk('setconsent', boolean)",
    sources: ['https://help.pinterest.com/en/business/article/track-conversions-with-pinterest-tag'],
  }),
  seed({
    id: 'snap.pixel',
    vendor: 'Snap Pixel',
    owner: 'Snap Inc.',
    match: { hosts: ['tr.snapchat.com', 'sc-static.net', 'snapchat.com'], inline: ['\\bsnaptr\\s*\\(', 'sc-static\\.net/scevent\\.min\\.js'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'hashed-email'],
    stores: [{ name: '^_scid', kind: 'cookie', lifetimeDays: 395 }],
    consentApi: 'none documented — must be held back',
    sources: ['https://businesshelp.snapchat.com/s/article/pixel-website-install'],
  }),
  seed({
    id: 'reddit.pixel',
    vendor: 'Reddit Pixel',
    owner: 'Reddit, Inc.',
    match: { hosts: ['alb.reddit.com', 'redditstatic.com', 'reddit.com'], inline: ['\\brdt\\s*\\(\\s*[\'"]init', 'redditstatic\\.com/ads/pixel\\.js', '\\brdt\\s*\\(\\s*["\'](init|track)["\']'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'hashed-email'],
    stores: [{ name: '^_rdt_uuid$', kind: 'cookie', lifetimeDays: 90 }],
    consentApi: "rdt('init', id, {optOut, useDecimalCurrencyValues}) — no documented consent API",
    sources: ['https://business.reddithelp.com/s/article/Reddit-Pixel'],
  }),
  seed({
    id: 'x.pixel',
    vendor: 'X (Twitter) Pixel',
    owner: 'X Corp.',
    match: { hosts: ['ads-twitter.com', 'analytics.twitter.com', 't.co', 'twitter.com', 'x.com'], inline: ['\\btwq\\s*\\(', 'static\\.ads-twitter\\.com/uwt\\.js'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    stores: [{ name: '^(personalization_id|muc_ads|guest_id.*)$', kind: 'cookie', lifetimeDays: 400 }],
    consentApi: 'none documented — must be held back',
    sources: ['https://business.x.com/en/help/campaign-measurement-and-analytics/conversion-tracking-for-websites'],
  }),
  seed({
    id: 'criteo',
    vendor: 'Criteo',
    owner: 'Criteo S.A.',
    match: { hosts: ['criteo.com', 'criteo.net'], inline: ['\\bcriteo_q\\b', 'static\\.criteo\\.net/js/ld/ld\\.js'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'hashed-email'],
    decoder: 'iab',
    sources: ['https://www.criteo.com/privacy/'],
  }),
  seed({
    id: 'amazon.ads',
    vendor: 'Amazon Advertising',
    owner: 'Amazon.com, Inc.',
    match: { hosts: ['amazon-adsystem.com'], inline: ['amazon-adsystem\\.com/aax2/apstag', '\\bamzn\\s*\\(\\s*["\']'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    decoder: 'iab',
    sources: ['https://advertising.amazon.com/'],
  }),
  seed({
    id: 'tradedesk',
    vendor: 'The Trade Desk',
    owner: 'The Trade Desk, Inc.',
    match: { hosts: ['adsrvr.org'], inline: ['js\\.adsrvr\\.org/up_loader', '\\bttd_dom_ready\\b'] },
    categories: ['advertising', 'identity-resolution'],
    sends: ['page-address', 'browser-id'],
    decoder: 'iab',
    notes: 'Unified ID 2.0 operator.',
    sources: ['https://www.thetradedesk.com/us/privacy'],
  }),
  seed({
    id: 'liveramp',
    vendor: 'LiveRamp',
    owner: 'LiveRamp Holdings, Inc.',
    match: { hosts: ['rlcdn.com', 'liveramp.com', 'pippio.com'], inline: ['ats\\.rlcdn\\.com/'] },
    categories: ['identity-resolution', 'advertising'],
    sends: ['browser-id', 'hashed-email'],
    decoder: 'iab',
    sources: ['https://liveramp.com/privacy/'],
  }),
  seed({
    id: 'taboola',
    vendor: 'Taboola',
    owner: 'Taboola.com Ltd.',
    match: { hosts: ['taboola.com', 'taboolasyndication.com'], inline: ['cdn\\.taboola\\.com/libtrc/', '\\b_tfa\\.push\\s*\\('] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    decoder: 'iab',
    sources: ['https://www.taboola.com/policies/privacy-policy'],
  }),
  seed({
    id: 'outbrain',
    vendor: 'Outbrain',
    owner: 'Outbrain Inc.',
    match: { hosts: ['outbrain.com', 'outbrainimg.com'], inline: ['amplify\\.outbrain\\.com/cp/obtp\\.js', '\\bobApi\\b'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    decoder: 'iab',
    sources: ['https://www.outbrain.com/privacy/'],
  }),
  seed({
    id: 'wunderkind',
    vendor: 'Wunderkind (BounceX)',
    owner: 'Wunderkind Corp.',
    match: { hosts: ['bounceexchange.com', 'bouncex.net', 'wknd.ai', 'cdnbasket.net'], inline: ['tag\\.wknd\\.ai/', 'bounceexchange\\.com/tag/'] },
    categories: ['identity-resolution', 'marketing-email'],
    sends: ['page-address', 'browser-id', 'hashed-email', 'form-input'],
    notes: 'Identity resolution named in Florida wiretap complaints (e.g. Magenheim v. Nike).',
    sources: ['https://www.wunderkind.co/privacy/'],
  }),

  // --- Analytics / session recording ----------------------------------------
  seed({
    id: 'hotjar',
    vendor: 'Hotjar',
    owner: 'Hotjar Ltd. (Contentsquare)',
    match: { hosts: ['hotjar.com', 'hotjar.io'], inline: ['\\b_hjSettings\\b', 'static\\.hotjar\\.com/c/hotjar-'] },
    categories: ['session-recording', 'analytics'],
    sends: ['page-address', 'browser-id', 'interactions'],
    stores: [{ name: '^_hj', kind: 'cookie', lifetimeDays: 365 }],
    consentApi: 'none — load the script only after consent',
    sources: ['https://help.hotjar.com/hc/en-us/articles/115011789248-Hotjar-Cookie-Information'],
  }),
  seed({
    id: 'contentsquare',
    vendor: 'Contentsquare',
    owner: 'Contentsquare SAS',
    match: { hosts: ['contentsquare.net', 'contentsquare.com'], inline: ['t\\.contentsquare\\.net/uxa/'] },
    categories: ['session-recording', 'analytics'],
    sends: ['page-address', 'browser-id', 'interactions'],
    stores: [{ name: '^_cs_', kind: 'cookie', lifetimeDays: 395 }],
    consentApi: "window._uxa.push(['optout']) / ['acceptRecording']",
    sources: ['https://docs.contentsquare.com/'],
  }),
  seed({
    id: 'fullstory',
    vendor: 'FullStory',
    owner: 'FullStory, Inc.',
    match: { hosts: ['fullstory.com'], inline: ['edge\\.fullstory\\.com/s/fs\\.js', '\\b_fs_org\\b'] },
    categories: ['session-recording'],
    sends: ['page-address', 'browser-id', 'interactions'],
    stores: [{ name: '^fs_', kind: 'cookie', lifetimeDays: 365 }],
    consentApi: "FS('setIdentity', …) / FS('shutdown') — capture consent via FS('setConsent')",
    sources: ['https://developer.fullstory.com/'],
  }),
  seed({
    id: 'mouseflow',
    vendor: 'Mouseflow',
    owner: 'Mouseflow ApS',
    match: { hosts: ['mouseflow.com'], inline: ['cdn\\.mouseflow\\.com/projects/', '\\b_mfq\\b'] },
    categories: ['session-recording'],
    sends: ['page-address', 'browser-id', 'interactions'],
    stores: [{ name: '^mf_', kind: 'cookie', lifetimeDays: 90 }],
    sources: ['https://mouseflow.com/legal/privacy-policy/'],
  }),
  seed({
    id: 'luckyorange',
    vendor: 'Lucky Orange',
    owner: 'Lucky Orange LLC',
    match: { hosts: ['luckyorange.com', 'luckyorange.net'], inline: ['tools\\.luckyorange\\.com/core/lo\\.js', '__lo_site_id'] },
    categories: ['session-recording'],
    sends: ['page-address', 'browser-id', 'interactions'],
    sources: ['https://www.luckyorange.com/privacy'],
  }),
  seed({
    id: 'segment',
    vendor: 'Segment',
    owner: 'Twilio Inc.',
    match: { hosts: ['segment.com', 'segment.io', 'segmentapis.com'], inline: ['cdn\\.segment\\.com/analytics\\.js/v1/', '\\banalytics\\.load\\s*\\(\\s*["\']'] },
    categories: ['analytics'],
    sends: ['page-address', 'browser-id', 'event-name'],
    stores: [{ name: '^ajs_', kind: 'cookie', lifetimeDays: 365 }],
    sources: ['https://segment.com/docs/privacy/'],
  }),
  seed({
    id: 'mixpanel',
    vendor: 'Mixpanel',
    owner: 'Mixpanel, Inc.',
    match: { hosts: ['mixpanel.com', 'mxpnl.com'], inline: ['cdn\\.mxpnl\\.com/libs/mixpanel', '\\bmixpanel\\.init\\s*\\('] },
    categories: ['analytics'],
    sends: ['page-address', 'browser-id', 'event-name'],
    stores: [{ name: '^mp_.*_mixpanel$', kind: 'cookie', lifetimeDays: 365 }],
    consentApi: 'mixpanel.opt_out_tracking() / opt_in_tracking()',
    sources: ['https://docs.mixpanel.com/docs/privacy'],
  }),
  seed({
    id: 'amplitude',
    vendor: 'Amplitude',
    owner: 'Amplitude, Inc.',
    match: { hosts: ['amplitude.com'], inline: ['cdn\\.amplitude\\.com/', '\\bamplitude\\.(getInstance|init)\\s*\\('] },
    categories: ['analytics'],
    sends: ['page-address', 'browser-id', 'event-name'],
    stores: [{ name: '^(amp_|AMP_)', kind: 'cookie', lifetimeDays: 365 }],
    consentApi: 'amplitude.setOptOut(true)',
    sources: ['https://amplitude.com/docs/data/sdks'],
  }),
  seed({
    id: 'heap',
    vendor: 'Heap',
    owner: 'Heap Inc. (Contentsquare)',
    match: { hosts: ['heap.io', 'heapanalytics.com'], inline: ['cdn\\.heapanalytics\\.com/js/heap-', '\\bheap\\.load\\s*\\('] },
    categories: ['analytics', 'session-recording'],
    sends: ['page-address', 'browser-id', 'interactions'],
    stores: [{ name: '^_hp2_', kind: 'cookie', lifetimeDays: 395 }],
    sources: ['https://developers.heap.io/'],
  }),
  seed({
    id: 'adobe.analytics',
    vendor: 'Adobe Experience Cloud',
    owner: 'Adobe Inc.',
    match: { hosts: ['omtrdc.net', 'demdex.net', 'adobedtm.com', 'everesttech.net'], inline: ['assets\\.adobedtm\\.com/', '\\.omtrdc\\.net'] },
    categories: ['analytics', 'advertising'],
    sends: ['page-address', 'browser-id'],
    stores: [{ name: '^(s_cc|s_sq|s_vi|AMCV_.*|demdex)$', kind: 'cookie', lifetimeDays: 395 }],
    sources: ['https://experienceleague.adobe.com/docs/core-services/interface/administration/ec-cookies/cookies-privacy.html'],
  }),
  seed({
    id: 'shopify.monorail',
    vendor: 'Shopify analytics (Monorail)',
    owner: 'Shopify Inc.',
    match: { hosts: ['monorail-edge.shopifysvc.com', 'shopifysvc.com'] },
    categories: ['analytics'],
    sends: ['page-address', 'browser-id', 'event-name'],
    stores: [{ name: '^(_shopify_y|_shopify_s|_shopify_sa_p|_shopify_sa_t|_shopify_analytics)$', kind: 'cookie', lifetimeDays: 365 }],
    consentApi: 'Shopify Customer Privacy API — customerPrivacy.setTrackingConsent({analytics, marketing, preferences, sale_of_data})',
    sources: ['https://shopify.dev/docs/api/customer-privacy'],
  }),
  seed({
    id: 'yahoo.ads',
    vendor: 'Yahoo Advertising',
    owner: 'Yahoo Inc.',
    match: { hosts: ['analytics.yahoo.com', 'ads.yahoo.com', 'yahoo.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    decoder: 'iab',
    sources: ['https://legal.yahoo.com/us/en/yahoo/privacy/index.html'],
  }),
  seed({
    id: 'quantcast',
    vendor: 'Quantcast',
    owner: 'Quantcast Corp.',
    match: { hosts: ['quantserve.com', 'quantcount.com', 'quantcast.com'], inline: ['quantserve\\.com/quant\\.js', '\\b_qevents\\b'] },
    categories: ['advertising', 'analytics'],
    sends: ['page-address', 'browser-id'],
    decoder: 'iab',
    sources: ['https://www.quantcast.com/privacy/'],
  }),

  // --- Marketing / email / SMS ----------------------------------------------
  seed({
    id: 'klaviyo',
    vendor: 'Klaviyo',
    owner: 'Klaviyo, Inc.',
    match: { hosts: ['klaviyo.com', 'klaviyo.net'], inline: ['\\b_learnq\\b', 'static\\.klaviyo\\.com/onsite/js/', '\\bklaviyo\\.init\\s*\\('] },
    categories: ['marketing-email', 'analytics'],
    sends: ['page-address', 'browser-id', 'hashed-email', 'form-input'],
    stores: [{ name: '^__kla_id$', kind: 'cookie', lifetimeDays: 730 }],
    consentApi: 'none documented for onsite tracking — hold back until consent',
    notes: 'Onsite tracking ties browsing to an email profile once identified; signup forms can send typed email before submit.',
    sources: ['https://help.klaviyo.com/hc/en-us/articles/115005076767'],
  }),
  seed({
    id: 'attentive',
    vendor: 'Attentive',
    owner: 'Attentive Mobile Inc.',
    match: { hosts: ['attn.tv', 'attentivemobile.com', 'attentive.com'], inline: ['cdn\\.attn\\.tv/[^/"\'\\s]+/dtag\\.js'] },
    categories: ['marketing-email', 'identity-resolution'],
    sends: ['page-address', 'browser-id', 'form-input'],
    sources: ['https://www.attentive.com/privacy'],
  }),
  seed({
    id: 'hubspot',
    vendor: 'HubSpot',
    owner: 'HubSpot, Inc.',
    match: { hosts: ['hubspot.com', 'hs-analytics.net', 'hs-scripts.com', 'hsforms.com', 'hs-banner.com', 'usemessages.com', 'hscollectedforms.net'], inline: ['js(-[a-z0-9]+)?\\.hs-scripts\\.com/', 'js\\.hs-analytics\\.net/', '\\b_hsq\\b'] },
    categories: ['analytics', 'marketing-email'],
    sends: ['page-address', 'browser-id', 'form-input'],
    stores: [{ name: '^(__hstc|hubspotutk|__hssc|__hssrc)$', kind: 'cookie', lifetimeDays: 180 }],
    consentApi: "_hsp.push(['addPrivacyConsentListener', …]); doNotTrack",
    sources: ['https://knowledge.hubspot.com/privacy-and-consent/what-cookies-does-hubspot-set-in-a-visitor-s-browser'],
  }),

  // --- Chat -----------------------------------------------------------------
  seed({
    id: 'intercom',
    vendor: 'Intercom',
    owner: 'Intercom, Inc.',
    match: { hosts: ['intercom.io', 'intercomcdn.com', 'intercomassets.com'], inline: ['widget\\.intercom\\.io/', '\\bintercomSettings\\b'] },
    categories: ['chat'],
    sends: ['page-address', 'browser-id'],
    stores: [{ name: '^intercom-', kind: 'cookie', lifetimeDays: 270 }],
    sources: ['https://www.intercom.com/help/en/articles/2361922-intercom-messenger-cookies'],
  }),
  seed({
    id: 'gorgias',
    vendor: 'Gorgias chat',
    owner: 'Gorgias Inc.',
    match: { hosts: ['gorgias.chat', 'gorgias.io', 'gorgias.help'], inline: ['config\\.gorgias\\.chat'] },
    categories: ['chat'],
    sends: ['page-address', 'browser-id'],
    sources: ['https://www.gorgias.com/legal/privacy'],
  }),
  seed({
    id: 'zendesk',
    vendor: 'Zendesk',
    owner: 'Zendesk, Inc.',
    match: { hosts: ['zdassets.com', 'zendesk.com', 'zopim.com'], inline: ['static\\.zdassets\\.com/ekr/snippet\\.js'] },
    categories: ['chat'],
    sends: ['page-address', 'browser-id'],
    sources: ['https://www.zendesk.com/company/agreements-and-terms/cookie-notice/'],
  }),
  seed({
    id: 'tidio',
    vendor: 'Tidio',
    owner: 'Tidio LLC',
    match: { hosts: ['tidio.co', 'tidiochat.com'], inline: ['code\\.tidio\\.co/'] },
    categories: ['chat'],
    sends: ['page-address', 'browser-id'],
    sources: ['https://www.tidio.com/privacy-policy/'],
  }),
  seed({
    id: 'livechat',
    vendor: 'LiveChat',
    owner: 'Text S.A.',
    match: { hosts: ['livechatinc.com', 'livechat.com'], inline: ['cdn\\.livechatinc\\.com/tracking\\.js', '__lc\\.license'] },
    categories: ['chat'],
    sends: ['page-address', 'browser-id'],
    sources: ['https://www.livechat.com/legal/privacy-policy/'],
  }),
  seed({
    id: 'drift',
    vendor: 'Drift',
    owner: 'Salesloft, Inc.',
    match: { hosts: ['drift.com', 'driftt.com', 'drift.cloud'], inline: ['js\\.driftt\\.com/'] },
    categories: ['chat'],
    sends: ['page-address', 'browser-id'],
    sources: ['https://www.salesloft.com/legal/cookie-notice'],
  }),

  // --- Reviews / embeds -----------------------------------------------------
  seed({
    id: 'yotpo',
    vendor: 'Yotpo',
    owner: 'Yotpo Ltd.',
    match: { hosts: ['yotpo.com', 'yotpoapps.com'], inline: ['staticw2\\.yotpo\\.com/'] },
    categories: ['reviews'],
    sends: ['page-address', 'browser-id'],
    sources: ['https://www.yotpo.com/privacy-policy/'],
  }),
  seed({
    id: 'vimeo',
    vendor: 'Vimeo embed',
    owner: 'Vimeo.com, Inc.',
    match: { hosts: ['vimeo.com', 'vimeocdn.com'] },
    categories: ['embed'],
    consentApi: 'dnt=1 on the player URL blocks session data and analytics',
    sources: ['https://vimeo.com/cookie_policy'],
  }),

  // --- Infrastructure -------------------------------------------------------
  seed({
    id: 'cloudflare',
    vendor: 'Cloudflare',
    owner: 'Cloudflare, Inc.',
    match: { hosts: ['cloudflare.com', 'cloudflareinsights.com', 'cdnjs.cloudflare.com'] },
    categories: ['cdn'],
    // Bot management and load balancing; set on the site's own domain or a vendor's behind Cloudflare.
    stores: [{ name: '^(__cf_bm|_cfuvid|cf_clearance|__cflb|__cfruid|cf_chl_.*)$', kind: 'cookie' }],
    notes: 'static.cloudflareinsights.com (Web Analytics beacon) is analytics without cookies — reviewed separately when seen.',
    sources: ['https://www.cloudflare.com/cookie-policy/', 'https://developers.cloudflare.com/fundamentals/reference/policies-compliances/cloudflare-cookies/'],
  }),
  seed({
    id: 'shopify.cdn',
    vendor: 'Shopify CDN',
    owner: 'Shopify Inc.',
    match: { hosts: ['cdn.shopify.com', 'shopifycdn.net', 'shopifycloud.com'] },
    categories: ['cdn'],
    sources: ['https://www.shopify.com/legal/cookies'],
  }),
  seed({
    id: 'shopify.shop-pay',
    vendor: 'Shop Pay',
    owner: 'Shopify Inc.',
    match: { hosts: ['shop.app', 'shopify.com'] },
    categories: ['payments'],
    sources: ['https://www.shopify.com/legal/cookies'],
  }),
  // Cookie-name entries: platform cookies a site sets on its own domain, so no
  // outside tool's category is there to inherit. Listed after the host entries
  // for the same vendors, so host lookups still find those first.
  seed({
    id: 'shopify.cookies.essential',
    vendor: 'Shopify store cookies (essential)',
    owner: 'Shopify Inc.',
    match: { hosts: ['shopify.com'] },
    categories: ['necessary'],
    stores: [{ name: '^(_shopify_essential|_shop_app_essential|_tracking_consent|_cmp_a|cart|cart_sig|cart_ts|cart_ver|cart_currency|secure_customer_sig|localization|_secure_session_id|keep_alive|_shopify_country|_storefront_u|checkout_session_token.*)$', kind: 'cookie' }],
    sources: ['https://www.shopify.com/legal/cookies'],
  }),
  seed({
    id: 'shopify.cookies.marketing',
    vendor: 'Shopify store cookies (marketing)',
    owner: 'Shopify Inc.',
    match: { hosts: ['shopify.com'] },
    categories: ['advertising'],
    stores: [{ name: '^_shopify_marketing$', kind: 'cookie' }],
    sources: ['https://www.shopify.com/legal/cookies'],
  }),
  seed({
    id: 'aws.load-balancer',
    vendor: 'AWS load balancer stickiness',
    owner: 'Amazon Web Services, Inc.',
    match: { hosts: ['elb.amazonaws.com'] },
    categories: ['necessary'],
    stores: [{ name: '^(AWSALB|AWSALBCORS|AWSALBTG|AWSALBTGCORS|AWSELB|AWSELBCORS)$', kind: 'cookie', lifetimeDays: 7 }],
    sources: ['https://docs.aws.amazon.com/elasticloadbalancing/latest/application/sticky-sessions.html'],
  }),
  seed({
    id: 'jsdelivr',
    vendor: 'Public JS CDNs (jsDelivr, unpkg)',
    match: { hosts: ['jsdelivr.net', 'unpkg.com', 'jquery.com'] },
    categories: ['cdn'],
    sources: ['https://www.jsdelivr.com/terms/privacy-policy-jsdelivr-net'],
  }),
  seed({
    id: 'typekit',
    vendor: 'Adobe Fonts (Typekit)',
    owner: 'Adobe Inc.',
    match: { hosts: ['typekit.net', 'typekit.com'] },
    categories: ['fonts'],
    sources: ['https://www.adobe.com/privacy/policies/adobe-fonts.html'],
  }),
  seed({
    id: 'stripe',
    vendor: 'Stripe',
    owner: 'Stripe, Inc.',
    match: { hosts: ['stripe.com', 'stripe.network'] },
    categories: ['payments'],
    stores: [{ name: '^__stripe_(mid|sid)$', kind: 'cookie', lifetimeDays: 365 }],
    notes: 'Fraud signals (m.stripe.com) — commonly argued strictly necessary for payment.',
    sources: ['https://stripe.com/cookie-settings'],
  }),
  seed({
    id: 'paypal',
    vendor: 'PayPal',
    owner: 'PayPal Holdings, Inc.',
    match: { hosts: ['paypal.com', 'paypalobjects.com'] },
    categories: ['payments'],
    sources: ['https://www.paypal.com/myaccount/privacy/cookiePrefs'],
  }),
  seed({
    id: 'hcaptcha',
    vendor: 'hCaptcha',
    owner: 'Intuition Machines, Inc.',
    match: { hosts: ['hcaptcha.com'] },
    categories: ['captcha'],
    sources: ['https://www.hcaptcha.com/privacy'],
  }),
  seed({
    id: 'sentry',
    vendor: 'Sentry',
    owner: 'Functional Software, Inc.',
    match: { hosts: ['sentry.io', 'sentry-cdn.com'], inline: ['browser\\.sentry-cdn\\.com/', '\\bSentry\\.init\\s*\\('] },
    categories: ['error-monitoring'],
    notes: 'Session Replay add-on is session recording — reviewed when replay payloads are seen.',
    sources: ['https://sentry.io/privacy/'],
  }),

  // --- Widgets / reviews (A8) ------------------------------------------------
  seed({
    id: 'elfsight',
    vendor: 'Elfsight widgets',
    owner: 'Elfsight LLC',
    match: { hosts: ['elfsight.com', 'elfsightcdn.com'] },
    categories: ['embed'],
    sends: ['page-address'],
    consentApi: 'none — gate the widget; social-feed widgets load the platforms’ own cookies',
    sources: ['https://help.elfsight.com/article/418-elfsight-and-gdpr'],
  }),
  seed({
    id: 'judgeme',
    vendor: 'Judge.me reviews',
    owner: 'Judge.me Ltd.',
    match: { hosts: ['judge.me'] },
    categories: ['reviews'],
    sends: ['page-address'],
    consentApi: 'none documented',
    sources: ['https://judge.me/help/en/articles/8364277-gdpr-compliance'],
  }),

  // --- Ad-tech exchanges (A8): TCF is their only consent signal -------------
  seed({
    id: 'magnite',
    vendor: 'Magnite (Rubicon Project)',
    owner: 'Magnite, Inc.',
    match: { hosts: ['rubiconproject.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    stores: [{ name: '^(khaos|khaos_p|trp_optout)$', kind: 'cookie' }],
    consentApi: 'IAB TCF / GPP only',
    decoder: 'iab',
    sources: ['https://gdpr.rubiconproject.com/dvplus/devicestoragedisclosure.json', 'https://www.magnite.com/legal/advertising-technology-privacy-policy/'],
  }),
  seed({
    id: 'pubmatic',
    vendor: 'PubMatic',
    owner: 'PubMatic, Inc.',
    match: { hosts: ['pubmatic.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    stores: [{ name: '^(KADUSERCOOKIE|KRTBCOOKIE_.*|SyncRTB\\d|DPSync\\d|PUBRETARGET|PugT|KCCH|USCC)$', kind: 'cookie' }],
    consentApi: 'IAB TCF / GPP only',
    decoder: 'iab',
    sources: ['https://cdn.pubmatic.com/devicestorage.json', 'https://pubmatic.com/legal/privacy/'],
  }),
  seed({
    id: 'indexexchange',
    vendor: 'Index Exchange',
    owner: 'Index Exchange Inc.',
    match: { hosts: ['casalemedia.com', 'indexww.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    stores: [{ name: '^(CMID|CMPS|CMPRO|CMO|CMTEST)$', kind: 'cookie' }],
    consentApi: 'IAB TCF / GPP only',
    decoder: 'iab',
    sources: ['https://cdn.indexexchange.com/device_storage_disclosure.json', 'https://www.indexexchange.com/privacy'],
  }),
  seed({
    id: 'openx',
    vendor: 'OpenX',
    owner: 'OpenX Technologies, Inc.',
    match: { hosts: ['openx.net'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    // Also sets i / pd (too generic to match by name alone).
    stores: [{ name: '^OX_dnt$', kind: 'cookie' }],
    consentApi: 'IAB TCF / GPP only',
    decoder: 'iab',
    sources: ['https://www.openx.com/device-storage.json', 'https://www.openx.com/privacy-center/openx-ad-exchange-privacy-policy/'],
  }),

  // --- Consent tools (their own traffic is necessary) -----------------------
  seed({
    id: 'consent.onetrust',
    vendor: 'OneTrust',
    owner: 'OneTrust LLC',
    match: { hosts: ['onetrust.com', 'cookielaw.org', 'cookiepro.com'], inline: ['cdn\\.cookielaw\\.org/scripttemplates/otSDKStub\\.js', '\\bOptanonWrapper\\b'] },
    categories: ['consent'],
    sources: ['https://developer.onetrust.com/'],
  }),
  seed({
    id: 'consent.cookiebot',
    vendor: 'Cookiebot',
    owner: 'Usercentrics A/S',
    match: { hosts: ['cookiebot.com', 'cookiebot.eu'], inline: ['consent\\.cookiebot\\.com/uc\\.js'] },
    categories: ['consent'],
    sources: ['https://www.cookiebot.com/en/developer/'],
  }),
  seed({
    id: 'consent.usercentrics',
    vendor: 'Usercentrics',
    owner: 'Usercentrics GmbH',
    match: { hosts: ['usercentrics.eu', 'usercentrics.com'], inline: ['app\\.usercentrics\\.eu/'] },
    categories: ['consent'],
    sources: ['https://docs.usercentrics.com/'],
  }),
  seed({
    id: 'consent.didomi',
    vendor: 'Didomi',
    owner: 'Didomi SAS',
    match: { hosts: ['privacy-center.org', 'didomi.io'], inline: ['sdk\\.privacy-center\\.org/'] },
    categories: ['consent'],
    sources: ['https://developers.didomi.io/'],
  }),
  seed({
    id: 'consent.trustarc',
    vendor: 'TrustArc',
    owner: 'TrustArc Inc.',
    match: { hosts: ['trustarc.com', 'truste.com'] },
    categories: ['consent'],
    sources: ['https://trustarc.com/'],
  }),
];

// Control facts (control.ts) attach by id; an entry that already carries its
// own `control` keeps it.
export const SEED_ENTRIES: KnowledgeEntryInput[] = BASE_ENTRIES.map((e) =>
  e.control || !CONTROL_FACTS[e.id] ? e : { ...e, control: CONTROL_FACTS[e.id] },
);
