import type { KnowledgeEntryInput } from './schema.js';

// Seed knowledge base. Every entry is a PROPOSAL (proposedBy 'complykit-seed',
// no confirmedBy): it lets the first scans name the common vendors, and each
// one waits for a human to confirm it through the research workflow (§4.2).
// Order matters — first match wins — so path-specific entries on shared hosts
// (google.com) come before broader ones.
//
// Sources are the vendors' own documentation roots. No data here is copied
// from the non-commercial tracker databases (Tracker Radar / Disconnect /
// Ghostery) — this repository is public (plans/consent-design.md §4.4).

const SEEDED = '2026-10-02';
const seed = (e: Omit<KnowledgeEntryInput, 'provenance'> & { sources?: string[] }): KnowledgeEntryInput => {
  const { sources, ...rest } = e;
  return { ...rest, provenance: { proposedBy: 'complykit-seed', proposedAt: SEEDED, sources: sources ?? [] } };
};

const GOOGLE_CONSENT = 'https://developers.google.com/tag-platform/security/guides/consent';

export const SEED_ENTRIES: KnowledgeEntryInput[] = [
  // --- Google ---------------------------------------------------------------
  seed({
    id: 'google.analytics',
    vendor: 'Google Analytics 4',
    owner: 'Google LLC',
    match: { hosts: ['google-analytics.com', 'analytics.google.com'] },
    categories: ['analytics'],
    sends: ['page-address', 'page-title', 'browser-id', 'event-name'],
    stores: [{ name: '^_ga(_.+)?$', kind: 'cookie', lifetimeDays: 400 }],
    consentApi: "Google Consent Mode — gtag('consent', 'update', {analytics_storage})",
    decoder: 'google',
    notes: 'Consent Mode "advanced" still sends cookieless pings with consent denied — decoded, not counted as consented traffic.',
    sources: [GOOGLE_CONSENT, 'https://support.google.com/analytics/answer/11397207'],
  }),
  seed({
    id: 'google.ads.ccm',
    vendor: 'Google Ads (conversion / remarketing)',
    owner: 'Google LLC',
    match: { hosts: ['google.com', 'google.co.uk', 'google.de', 'google.ca'], path: '^/(pagead|ccm|rmkt|ads)/' },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'click-id'],
    consentApi: "Google Consent Mode — ad_storage, ad_user_data, ad_personalization",
    decoder: 'google',
    restrictedMode: 'rdp=1 (restricted data processing) / npa=1',
    sources: [GOOGLE_CONSENT],
  }),
  seed({
    id: 'google.recaptcha',
    vendor: 'Google reCAPTCHA',
    owner: 'Google LLC',
    match: { hosts: ['google.com', 'recaptcha.net', 'gstatic.com'], path: '^/recaptcha/' },
    categories: ['captcha'],
    consentApi: 'none — load only where the form needs it',
    notes: 'EU DPAs have treated reCAPTCHA on page load (not on interaction) as needing consent.',
    sources: ['https://developers.google.com/recaptcha'],
  }),
  seed({
    id: 'google.ads.doubleclick',
    vendor: 'Google Marketing Platform (DoubleClick)',
    owner: 'Google LLC',
    match: { hosts: ['doubleclick.net', 'googleadservices.com', 'googlesyndication.com', 'googletagservices.com', 'adservice.google.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'click-id'],
    stores: [{ name: '^(IDE|test_cookie|DSID)$', kind: 'cookie', lifetimeDays: 390 }, { name: '^_gcl_', kind: 'cookie', lifetimeDays: 90 }],
    consentApi: 'Google Consent Mode — ad_storage, ad_user_data, ad_personalization',
    decoder: 'google',
    restrictedMode: 'rdp=1 / npa=1',
    sources: [GOOGLE_CONSENT],
  }),
  seed({
    id: 'google.tag-manager',
    vendor: 'Google Tag Manager / gtag.js',
    owner: 'Google LLC',
    match: { hosts: ['googletagmanager.com'] },
    categories: ['tag-manager'],
    sends: ['page-address'],
    consentApi: 'loads other tags; gate those, and set Consent Mode defaults before it loads',
    decoder: 'google',
    notes: 'Loading the container script sends the page address to Google; whether that alone needs consent is unsettled.',
    sources: ['https://developers.google.com/tag-platform/tag-manager'],
  }),
  seed({
    id: 'google.fonts',
    vendor: 'Google Fonts',
    owner: 'Google LLC',
    match: { hosts: ['fonts.googleapis.com', 'fonts.gstatic.com'] },
    categories: ['fonts'],
    consentApi: 'none — self-host the fonts',
    notes: 'LG München (2022) held loading Google Fonts from Google’s servers without consent unlawful in DE.',
    sources: ['https://developers.google.com/fonts/faq/privacy'],
  }),
  seed({
    id: 'google.maps',
    vendor: 'Google Maps',
    owner: 'Google LLC',
    match: { hosts: ['maps.googleapis.com', 'maps.gstatic.com'] },
    categories: ['embed'],
    consentApi: 'none — load on interaction (two-click facade)',
    sources: ['https://developers.google.com/maps'],
  }),
  seed({
    id: 'google.youtube',
    vendor: 'YouTube embed',
    owner: 'Google LLC',
    match: { hosts: ['youtube.com', 'youtube-nocookie.com', 'ytimg.com', 'googlevideo.com'] },
    categories: ['embed'],
    stores: [{ name: '^(VISITOR_INFO1_LIVE|YSC|VISITOR_PRIVACY_METADATA)$', kind: 'cookie', lifetimeDays: 180 }],
    consentApi: 'none — youtube-nocookie limits personalization only; use a click-to-load facade',
    sources: ['https://support.google.com/youtube/answer/171780'],
  }),
  seed({
    id: 'google.services',
    vendor: 'Google (google.com services)',
    owner: 'Google LLC',
    // Everything on google.com the path-specific entries above didn't claim.
    match: { hosts: ['google.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    stores: [{ name: '^(NID|AEC|1P_JAR|SOCS|__Secure-ENID)$', kind: 'cookie', lifetimeDays: 183 }],
    consentApi: 'none for widgets — load on interaction or after consent',
    notes: 'Widgets served from google.com (e.g. the merchant-review badge) set NID, which Google’s cookie policy lists for ads in Google services.',
    sources: ['https://policies.google.com/technologies/cookies'],
  }),
  seed({
    id: 'google.static',
    vendor: 'Google static assets',
    owner: 'Google LLC',
    match: { hosts: ['gstatic.com', 'googleapis.com'] },
    categories: ['cdn'],
    sources: ['https://policies.google.com/technologies'],
  }),

  // --- Meta -----------------------------------------------------------------
  seed({
    id: 'meta.pixel',
    vendor: 'Meta Pixel',
    owner: 'Meta Platforms, Inc.',
    match: { hosts: ['facebook.com', 'facebook.net', 'fbcdn.net'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'hashed-email', 'event-name', 'click-id'],
    stores: [{ name: '^_fb[pc]$', kind: 'cookie', lifetimeDays: 90 }],
    consentApi: "fbq('consent', 'revoke' | 'grant'); limited data use via fbq('dataProcessingOptions', ['LDU'], 0, 0)",
    decoder: 'meta',
    restrictedMode: 'Limited Data Use (dpo=LDU)',
    sources: ['https://developers.facebook.com/docs/meta-pixel/', 'https://developers.facebook.com/docs/marketing-apis/data-processing-options'],
  }),
  seed({
    id: 'meta.instagram',
    vendor: 'Instagram embed',
    owner: 'Meta Platforms, Inc.',
    match: { hosts: ['instagram.com', 'cdninstagram.com'] },
    categories: ['embed'],
    sources: ['https://developers.facebook.com/docs/instagram-platform/embed'],
  }),

  // --- Other ad platforms ---------------------------------------------------
  seed({
    id: 'tiktok.pixel',
    vendor: 'TikTok Pixel',
    owner: 'TikTok Pte. Ltd. / ByteDance',
    match: { hosts: ['analytics.tiktok.com', 'tiktok.com', 'tiktokcdn.com', 'tiktokw.us', 'ttwstatic.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'hashed-email', 'event-name', 'click-id'],
    stores: [{ name: '^_ttp$', kind: 'cookie', lifetimeDays: 390 }, { name: '^ttcsid', kind: 'cookie' }],
    consentApi: 'ttq.holdConsent() / ttq.grantConsent() / ttq.revokeConsent()',
    decoder: 'tiktok',
    restrictedMode: 'limited_data_use',
    sources: ['https://ads.tiktok.com/help/article/get-started-pixel'],
  }),
  seed({
    id: 'microsoft.uet',
    vendor: 'Microsoft Advertising UET',
    owner: 'Microsoft Corporation',
    match: { hosts: ['bat.bing.com', 'bat.bing.net', 'bing.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'click-id'],
    stores: [{ name: '^_uet(sid|vid)$', kind: 'cookie', lifetimeDays: 390 }, { name: '^MUID$', kind: 'cookie', lifetimeDays: 390 }],
    consentApi: "window.uetq.push('consent', 'update', {ad_storage})",
    decoder: 'microsoft',
    sources: ['https://learn.microsoft.com/en-us/advertising/guides/universal-event-tracking'],
  }),
  seed({
    id: 'microsoft.clarity',
    vendor: 'Microsoft Clarity',
    owner: 'Microsoft Corporation',
    match: { hosts: ['clarity.ms'] },
    categories: ['session-recording', 'analytics'],
    sends: ['page-address', 'browser-id', 'interactions'],
    stores: [{ name: '^_cl(ck|sk)$', kind: 'cookie', lifetimeDays: 365 }],
    consentApi: "clarity('consentv2', {ad_Storage, analytics_Storage})",
    sources: ['https://learn.microsoft.com/en-us/clarity/setup-and-installation/clarity-consent-api-v2'],
  }),
  seed({
    id: 'linkedin.insight',
    vendor: 'LinkedIn Insight Tag',
    owner: 'LinkedIn Corporation (Microsoft)',
    match: { hosts: ['px.ads.linkedin.com', 'snap.licdn.com', 'linkedin.com', 'licdn.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    stores: [{ name: '^(li_sugr|bcookie|lidc|UserMatchHistory|AnalyticsSyncHistory|li_fat_id)$', kind: 'cookie', lifetimeDays: 90 }],
    consentApi: 'none documented — must be held back',
    sources: ['https://www.linkedin.com/help/lms/answer/a427660'],
  }),
  seed({
    id: 'pinterest.tag',
    vendor: 'Pinterest Tag',
    owner: 'Pinterest, Inc.',
    match: { hosts: ['ct.pinterest.com', 'pinterest.com', 'pinimg.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'hashed-email', 'event-name'],
    stores: [{ name: '^_pin_unauth$|^_pinterest_', kind: 'cookie', lifetimeDays: 365 }],
    consentApi: "pintrk('setconsent', boolean)",
    sources: ['https://help.pinterest.com/en/business/article/track-conversions-with-pinterest-tag'],
  }),
  seed({
    id: 'snap.pixel',
    vendor: 'Snap Pixel',
    owner: 'Snap Inc.',
    match: { hosts: ['tr.snapchat.com', 'sc-static.net', 'snapchat.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'hashed-email'],
    stores: [{ name: '^_scid', kind: 'cookie', lifetimeDays: 395 }],
    consentApi: 'none documented — must be held back',
    sources: ['https://businesshelp.snapchat.com/s/article/pixel-website-install'],
  }),
  seed({
    id: 'reddit.pixel',
    vendor: 'Reddit Pixel',
    owner: 'Reddit, Inc.',
    match: { hosts: ['alb.reddit.com', 'redditstatic.com', 'reddit.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'hashed-email'],
    stores: [{ name: '^_rdt_uuid$', kind: 'cookie', lifetimeDays: 90 }],
    consentApi: "rdt('init', id, {optOut, useDecimalCurrencyValues}) — no documented consent API",
    sources: ['https://business.reddithelp.com/s/article/Reddit-Pixel'],
  }),
  seed({
    id: 'x.pixel',
    vendor: 'X (Twitter) Pixel',
    owner: 'X Corp.',
    match: { hosts: ['ads-twitter.com', 'analytics.twitter.com', 't.co', 'twitter.com', 'x.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    stores: [{ name: '^(personalization_id|muc_ads|guest_id.*)$', kind: 'cookie', lifetimeDays: 400 }],
    consentApi: 'none documented — must be held back',
    sources: ['https://business.x.com/en/help/campaign-measurement-and-analytics/conversion-tracking-for-websites'],
  }),
  seed({
    id: 'criteo',
    vendor: 'Criteo',
    owner: 'Criteo S.A.',
    match: { hosts: ['criteo.com', 'criteo.net'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id', 'hashed-email'],
    decoder: 'iab',
    sources: ['https://www.criteo.com/privacy/'],
  }),
  seed({
    id: 'amazon.ads',
    vendor: 'Amazon Advertising',
    owner: 'Amazon.com, Inc.',
    match: { hosts: ['amazon-adsystem.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    decoder: 'iab',
    sources: ['https://advertising.amazon.com/'],
  }),
  seed({
    id: 'tradedesk',
    vendor: 'The Trade Desk',
    owner: 'The Trade Desk, Inc.',
    match: { hosts: ['adsrvr.org'] },
    categories: ['advertising', 'identity-resolution'],
    sends: ['page-address', 'browser-id'],
    decoder: 'iab',
    notes: 'Unified ID 2.0 operator.',
    sources: ['https://www.thetradedesk.com/us/privacy'],
  }),
  seed({
    id: 'liveramp',
    vendor: 'LiveRamp',
    owner: 'LiveRamp Holdings, Inc.',
    match: { hosts: ['rlcdn.com', 'liveramp.com', 'pippio.com'] },
    categories: ['identity-resolution', 'advertising'],
    sends: ['browser-id', 'hashed-email'],
    decoder: 'iab',
    sources: ['https://liveramp.com/privacy/'],
  }),
  seed({
    id: 'taboola',
    vendor: 'Taboola',
    owner: 'Taboola.com Ltd.',
    match: { hosts: ['taboola.com', 'taboolasyndication.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    decoder: 'iab',
    sources: ['https://www.taboola.com/policies/privacy-policy'],
  }),
  seed({
    id: 'outbrain',
    vendor: 'Outbrain',
    owner: 'Outbrain Inc.',
    match: { hosts: ['outbrain.com', 'outbrainimg.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    decoder: 'iab',
    sources: ['https://www.outbrain.com/privacy/'],
  }),
  seed({
    id: 'wunderkind',
    vendor: 'Wunderkind (BounceX)',
    owner: 'Wunderkind Corp.',
    match: { hosts: ['bounceexchange.com', 'bouncex.net', 'wknd.ai', 'cdnbasket.net'] },
    categories: ['identity-resolution', 'marketing-email'],
    sends: ['page-address', 'browser-id', 'hashed-email', 'form-input'],
    notes: 'Identity resolution named in Florida wiretap complaints (e.g. Magenheim v. Nike).',
    sources: ['https://www.wunderkind.co/privacy/'],
  }),

  // --- Analytics / session recording ----------------------------------------
  seed({
    id: 'hotjar',
    vendor: 'Hotjar',
    owner: 'Hotjar Ltd. (Contentsquare)',
    match: { hosts: ['hotjar.com', 'hotjar.io'] },
    categories: ['session-recording', 'analytics'],
    sends: ['page-address', 'browser-id', 'interactions'],
    stores: [{ name: '^_hj', kind: 'cookie', lifetimeDays: 365 }],
    consentApi: 'none — load the script only after consent',
    sources: ['https://help.hotjar.com/hc/en-us/articles/115011789248-Hotjar-Cookie-Information'],
  }),
  seed({
    id: 'contentsquare',
    vendor: 'Contentsquare',
    owner: 'Contentsquare SAS',
    match: { hosts: ['contentsquare.net', 'contentsquare.com'] },
    categories: ['session-recording', 'analytics'],
    sends: ['page-address', 'browser-id', 'interactions'],
    stores: [{ name: '^_cs_', kind: 'cookie', lifetimeDays: 395 }],
    consentApi: "window._uxa.push(['optout']) / ['acceptRecording']",
    sources: ['https://docs.contentsquare.com/'],
  }),
  seed({
    id: 'fullstory',
    vendor: 'FullStory',
    owner: 'FullStory, Inc.',
    match: { hosts: ['fullstory.com'] },
    categories: ['session-recording'],
    sends: ['page-address', 'browser-id', 'interactions'],
    stores: [{ name: '^fs_', kind: 'cookie', lifetimeDays: 365 }],
    consentApi: "FS('setIdentity', …) / FS('shutdown') — capture consent via FS('setConsent')",
    sources: ['https://developer.fullstory.com/'],
  }),
  seed({
    id: 'mouseflow',
    vendor: 'Mouseflow',
    owner: 'Mouseflow ApS',
    match: { hosts: ['mouseflow.com'] },
    categories: ['session-recording'],
    sends: ['page-address', 'browser-id', 'interactions'],
    stores: [{ name: '^mf_', kind: 'cookie', lifetimeDays: 90 }],
    sources: ['https://mouseflow.com/legal/privacy-policy/'],
  }),
  seed({
    id: 'luckyorange',
    vendor: 'Lucky Orange',
    owner: 'Lucky Orange LLC',
    match: { hosts: ['luckyorange.com', 'luckyorange.net'] },
    categories: ['session-recording'],
    sends: ['page-address', 'browser-id', 'interactions'],
    sources: ['https://www.luckyorange.com/privacy'],
  }),
  seed({
    id: 'segment',
    vendor: 'Segment',
    owner: 'Twilio Inc.',
    match: { hosts: ['segment.com', 'segment.io', 'segmentapis.com'] },
    categories: ['analytics'],
    sends: ['page-address', 'browser-id', 'event-name'],
    stores: [{ name: '^ajs_', kind: 'cookie', lifetimeDays: 365 }],
    sources: ['https://segment.com/docs/privacy/'],
  }),
  seed({
    id: 'mixpanel',
    vendor: 'Mixpanel',
    owner: 'Mixpanel, Inc.',
    match: { hosts: ['mixpanel.com', 'mxpnl.com'] },
    categories: ['analytics'],
    sends: ['page-address', 'browser-id', 'event-name'],
    stores: [{ name: '^mp_.*_mixpanel$', kind: 'cookie', lifetimeDays: 365 }],
    consentApi: 'mixpanel.opt_out_tracking() / opt_in_tracking()',
    sources: ['https://docs.mixpanel.com/docs/privacy'],
  }),
  seed({
    id: 'amplitude',
    vendor: 'Amplitude',
    owner: 'Amplitude, Inc.',
    match: { hosts: ['amplitude.com'] },
    categories: ['analytics'],
    sends: ['page-address', 'browser-id', 'event-name'],
    stores: [{ name: '^(amp_|AMP_)', kind: 'cookie', lifetimeDays: 365 }],
    consentApi: 'amplitude.setOptOut(true)',
    sources: ['https://amplitude.com/docs/data/sdks'],
  }),
  seed({
    id: 'heap',
    vendor: 'Heap',
    owner: 'Heap Inc. (Contentsquare)',
    match: { hosts: ['heap.io', 'heapanalytics.com'] },
    categories: ['analytics', 'session-recording'],
    sends: ['page-address', 'browser-id', 'interactions'],
    stores: [{ name: '^_hp2_', kind: 'cookie', lifetimeDays: 395 }],
    sources: ['https://developers.heap.io/'],
  }),
  seed({
    id: 'adobe.analytics',
    vendor: 'Adobe Experience Cloud',
    owner: 'Adobe Inc.',
    match: { hosts: ['omtrdc.net', 'demdex.net', 'adobedtm.com', 'everesttech.net'] },
    categories: ['analytics', 'advertising'],
    sends: ['page-address', 'browser-id'],
    stores: [{ name: '^(s_cc|s_sq|s_vi|AMCV_.*|demdex)$', kind: 'cookie', lifetimeDays: 395 }],
    sources: ['https://experienceleague.adobe.com/docs/core-services/interface/administration/ec-cookies/cookies-privacy.html'],
  }),
  seed({
    id: 'shopify.monorail',
    vendor: 'Shopify analytics (Monorail)',
    owner: 'Shopify Inc.',
    match: { hosts: ['monorail-edge.shopifysvc.com', 'shopifysvc.com'] },
    categories: ['analytics'],
    sends: ['page-address', 'browser-id', 'event-name'],
    stores: [{ name: '^(_shopify_y|_shopify_s|_shopify_sa_p|_shopify_sa_t)$', kind: 'cookie', lifetimeDays: 365 }],
    consentApi: 'Shopify Customer Privacy API — customerPrivacy.setTrackingConsent({analytics, marketing, preferences, sale_of_data})',
    sources: ['https://shopify.dev/docs/api/customer-privacy'],
  }),
  seed({
    id: 'yahoo.ads',
    vendor: 'Yahoo Advertising',
    owner: 'Yahoo Inc.',
    match: { hosts: ['analytics.yahoo.com', 'ads.yahoo.com', 'yahoo.com'] },
    categories: ['advertising'],
    sends: ['page-address', 'browser-id'],
    decoder: 'iab',
    sources: ['https://legal.yahoo.com/us/en/yahoo/privacy/index.html'],
  }),
  seed({
    id: 'quantcast',
    vendor: 'Quantcast',
    owner: 'Quantcast Corp.',
    match: { hosts: ['quantserve.com', 'quantcount.com', 'quantcast.com'] },
    categories: ['advertising', 'analytics'],
    sends: ['page-address', 'browser-id'],
    decoder: 'iab',
    sources: ['https://www.quantcast.com/privacy/'],
  }),

  // --- Marketing / email / SMS ----------------------------------------------
  seed({
    id: 'klaviyo',
    vendor: 'Klaviyo',
    owner: 'Klaviyo, Inc.',
    match: { hosts: ['klaviyo.com', 'klaviyo.net'] },
    categories: ['marketing-email', 'analytics'],
    sends: ['page-address', 'browser-id', 'hashed-email', 'form-input'],
    stores: [{ name: '^__kla_id$', kind: 'cookie', lifetimeDays: 730 }],
    consentApi: 'none documented for onsite tracking — hold back until consent',
    notes: 'Onsite tracking ties browsing to an email profile once identified; signup forms can send typed email before submit.',
    sources: ['https://help.klaviyo.com/hc/en-us/articles/115005076767'],
  }),
  seed({
    id: 'attentive',
    vendor: 'Attentive',
    owner: 'Attentive Mobile Inc.',
    match: { hosts: ['attn.tv', 'attentivemobile.com', 'attentive.com'] },
    categories: ['marketing-email', 'identity-resolution'],
    sends: ['page-address', 'browser-id', 'form-input'],
    sources: ['https://www.attentive.com/privacy'],
  }),
  seed({
    id: 'hubspot',
    vendor: 'HubSpot',
    owner: 'HubSpot, Inc.',
    match: { hosts: ['hubspot.com', 'hs-analytics.net', 'hs-scripts.com', 'hsforms.com', 'hs-banner.com', 'usemessages.com', 'hscollectedforms.net'] },
    categories: ['analytics', 'marketing-email'],
    sends: ['page-address', 'browser-id', 'form-input'],
    stores: [{ name: '^(__hstc|hubspotutk|__hssc|__hssrc)$', kind: 'cookie', lifetimeDays: 180 }],
    consentApi: "_hsp.push(['addPrivacyConsentListener', …]); doNotTrack",
    sources: ['https://knowledge.hubspot.com/privacy-and-consent/what-cookies-does-hubspot-set-in-a-visitor-s-browser'],
  }),

  // --- Chat -----------------------------------------------------------------
  seed({
    id: 'intercom',
    vendor: 'Intercom',
    owner: 'Intercom, Inc.',
    match: { hosts: ['intercom.io', 'intercomcdn.com', 'intercomassets.com'] },
    categories: ['chat'],
    sends: ['page-address', 'browser-id'],
    stores: [{ name: '^intercom-', kind: 'cookie', lifetimeDays: 270 }],
    sources: ['https://www.intercom.com/help/en/articles/2361922-intercom-messenger-cookies'],
  }),
  seed({
    id: 'gorgias',
    vendor: 'Gorgias chat',
    owner: 'Gorgias Inc.',
    match: { hosts: ['gorgias.chat', 'gorgias.io', 'gorgias.help'] },
    categories: ['chat'],
    sends: ['page-address', 'browser-id'],
    sources: ['https://www.gorgias.com/legal/privacy'],
  }),
  seed({
    id: 'zendesk',
    vendor: 'Zendesk',
    owner: 'Zendesk, Inc.',
    match: { hosts: ['zdassets.com', 'zendesk.com', 'zopim.com'] },
    categories: ['chat'],
    sends: ['page-address', 'browser-id'],
    sources: ['https://www.zendesk.com/company/agreements-and-terms/cookie-notice/'],
  }),
  seed({
    id: 'tidio',
    vendor: 'Tidio',
    owner: 'Tidio LLC',
    match: { hosts: ['tidio.co', 'tidiochat.com'] },
    categories: ['chat'],
    sends: ['page-address', 'browser-id'],
    sources: ['https://www.tidio.com/privacy-policy/'],
  }),
  seed({
    id: 'livechat',
    vendor: 'LiveChat',
    owner: 'Text S.A.',
    match: { hosts: ['livechatinc.com', 'livechat.com'] },
    categories: ['chat'],
    sends: ['page-address', 'browser-id'],
    sources: ['https://www.livechat.com/legal/privacy-policy/'],
  }),
  seed({
    id: 'drift',
    vendor: 'Drift',
    owner: 'Salesloft, Inc.',
    match: { hosts: ['drift.com', 'driftt.com', 'drift.cloud'] },
    categories: ['chat'],
    sends: ['page-address', 'browser-id'],
    sources: ['https://www.salesloft.com/legal/cookie-notice'],
  }),

  // --- Reviews / embeds -----------------------------------------------------
  seed({
    id: 'yotpo',
    vendor: 'Yotpo',
    owner: 'Yotpo Ltd.',
    match: { hosts: ['yotpo.com', 'yotpoapps.com'] },
    categories: ['reviews'],
    sends: ['page-address', 'browser-id'],
    sources: ['https://www.yotpo.com/privacy-policy/'],
  }),
  seed({
    id: 'vimeo',
    vendor: 'Vimeo embed',
    owner: 'Vimeo.com, Inc.',
    match: { hosts: ['vimeo.com', 'vimeocdn.com'] },
    categories: ['embed'],
    consentApi: 'dnt=1 on the player URL blocks session data and analytics',
    sources: ['https://vimeo.com/cookie_policy'],
  }),

  // --- Infrastructure -------------------------------------------------------
  seed({
    id: 'cloudflare',
    vendor: 'Cloudflare',
    owner: 'Cloudflare, Inc.',
    match: { hosts: ['cloudflare.com', 'cloudflareinsights.com', 'cdnjs.cloudflare.com'] },
    categories: ['cdn'],
    notes: 'static.cloudflareinsights.com (Web Analytics beacon) is analytics without cookies — reviewed separately when seen.',
    sources: ['https://www.cloudflare.com/cookie-policy/'],
  }),
  seed({
    id: 'shopify.cdn',
    vendor: 'Shopify CDN',
    owner: 'Shopify Inc.',
    match: { hosts: ['cdn.shopify.com', 'shopifycdn.net', 'shopifycloud.com'] },
    categories: ['cdn'],
    sources: ['https://www.shopify.com/legal/cookies'],
  }),
  seed({
    id: 'shopify.shop-pay',
    vendor: 'Shop Pay',
    owner: 'Shopify Inc.',
    match: { hosts: ['shop.app', 'shopify.com'] },
    categories: ['payments'],
    sources: ['https://www.shopify.com/legal/cookies'],
  }),
  seed({
    id: 'jsdelivr',
    vendor: 'Public JS CDNs (jsDelivr, unpkg)',
    match: { hosts: ['jsdelivr.net', 'unpkg.com', 'jquery.com'] },
    categories: ['cdn'],
    sources: ['https://www.jsdelivr.com/terms/privacy-policy-jsdelivr-net'],
  }),
  seed({
    id: 'typekit',
    vendor: 'Adobe Fonts (Typekit)',
    owner: 'Adobe Inc.',
    match: { hosts: ['typekit.net', 'typekit.com'] },
    categories: ['fonts'],
    sources: ['https://www.adobe.com/privacy/policies/adobe-fonts.html'],
  }),
  seed({
    id: 'stripe',
    vendor: 'Stripe',
    owner: 'Stripe, Inc.',
    match: { hosts: ['stripe.com', 'stripe.network'] },
    categories: ['payments'],
    stores: [{ name: '^__stripe_(mid|sid)$', kind: 'cookie', lifetimeDays: 365 }],
    notes: 'Fraud signals (m.stripe.com) — commonly argued strictly necessary for payment.',
    sources: ['https://stripe.com/cookie-settings'],
  }),
  seed({
    id: 'paypal',
    vendor: 'PayPal',
    owner: 'PayPal Holdings, Inc.',
    match: { hosts: ['paypal.com', 'paypalobjects.com'] },
    categories: ['payments'],
    sources: ['https://www.paypal.com/myaccount/privacy/cookiePrefs'],
  }),
  seed({
    id: 'hcaptcha',
    vendor: 'hCaptcha',
    owner: 'Intuition Machines, Inc.',
    match: { hosts: ['hcaptcha.com'] },
    categories: ['captcha'],
    sources: ['https://www.hcaptcha.com/privacy'],
  }),
  seed({
    id: 'sentry',
    vendor: 'Sentry',
    owner: 'Functional Software, Inc.',
    match: { hosts: ['sentry.io', 'sentry-cdn.com'] },
    categories: ['error-monitoring'],
    notes: 'Session Replay add-on is session recording — reviewed when replay payloads are seen.',
    sources: ['https://sentry.io/privacy/'],
  }),

  // --- Consent tools (their own traffic is necessary) -----------------------
  seed({
    id: 'consent.onetrust',
    vendor: 'OneTrust',
    owner: 'OneTrust LLC',
    match: { hosts: ['onetrust.com', 'cookielaw.org', 'cookiepro.com'] },
    categories: ['consent'],
    sources: ['https://developer.onetrust.com/'],
  }),
  seed({
    id: 'consent.cookiebot',
    vendor: 'Cookiebot',
    owner: 'Usercentrics A/S',
    match: { hosts: ['cookiebot.com', 'cookiebot.eu'] },
    categories: ['consent'],
    sources: ['https://www.cookiebot.com/en/developer/'],
  }),
  seed({
    id: 'consent.usercentrics',
    vendor: 'Usercentrics',
    owner: 'Usercentrics GmbH',
    match: { hosts: ['usercentrics.eu', 'usercentrics.com'] },
    categories: ['consent'],
    sources: ['https://docs.usercentrics.com/'],
  }),
  seed({
    id: 'consent.didomi',
    vendor: 'Didomi',
    owner: 'Didomi SAS',
    match: { hosts: ['privacy-center.org', 'didomi.io'] },
    categories: ['consent'],
    sources: ['https://developers.didomi.io/'],
  }),
  seed({
    id: 'consent.trustarc',
    vendor: 'TrustArc',
    owner: 'TrustArc Inc.',
    match: { hosts: ['trustarc.com', 'truste.com'] },
    categories: ['consent'],
    sources: ['https://trustarc.com/'],
  }),
];
